### ISSUE TITLE
✨ [FEATURE]: Initial lib release

### ISSUE THREAD

**Issue by thinkjrs** [Tincre/promo-button#1]
This issue tracks the bare bones steps for our initial button lib release.

## Tasks

- [x] cleanup default inputs, 
- [x] fix the cloudinary overlay, 
- [x] add link/form-input default/placeholder customizability, 
- [x] better default logo (not b00st or its alt text), 
- [x] cleanup the default styling, 
- [x] ~#11~Coming feature
- [x] Add basic README documentation to replace dts-cli boilerplate
- [x] add the backend api routes instead of our local routes (they're what we use in b00st.com right now), 
- [x] fix the link selection bubbles,
- [x] figure out what we're doing for support, and lastly,
- [x] a simple request module/function to send the actual request to our backend (handling access tokens + refresh)
- [x] release the package on npm 
- [x] #15
- [x] shrink react-icons bundle
- [x] rename from `BButton` to `PromoButton`
- [x] ~#9~ Out of scope for this issue
- [x] refactor nextjs example herein to use npm versioned promo-button package `yarn add -D @tincre/promo-button`
- [x] fix nextjs example css imports
- [x] ~refactor example app render to `common` directory~Keeping as is, for now
- [x] update license to Mozilla Public License 2.0

**Comment by thinkjrs** [comment]
The bundle is huge due to react-icons, which we're fixing.

**Comment by thinkjrs** [comment]
- [ ] small discourse deployment for clients + steps
- [ ]

**Comment by thinkjrs** [comment]
The TODO above:

> figure out what we're doing for support, and lastly,

is being handled by the discourse instances launched.
